# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'dyte-swift-example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'DyteSdk', :git => 'https://github.com/dyte-in/dyte-ios-sdk', :branch => 'test/v1.8'
  # Pods for dyte-swift-example

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end